name: snowflake-devops-demo

# Controls when the action will run. 
on:
  push:
    branches:
      - main
    paths:
      - 'snowflake/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upgrade snowflake-connector and schemachange
        run: |
          pip install --upgrade schemachange snowflake-connector-python certifi

      - name: Upgrade Snowflake Connector
        run: pip install --upgrade snowflake-connector-python

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Print SF_ACCOUNT
        env:
          SF_ACCOUNT: "AJA98516"
          SF_USERNAME: "STRIVER"
          SF_ROLE: "ACCOUNTADMIN"
          SF_WAREHOUSE: "COMPUTE_WH"
          SF_DATABASE: "SNOWFLAKE_LEARNING_DB"
          SNOWFLAKE_PASSWORD: "MistyStriver@17"
        run: echo "SF_ACCOUNT is:$SF_ACCOUNT"

      - name: Run schemachange
        env:
         SF_ACCOUNT: "AJA98516"
         SF_USERNAME: "STRIVER"
         SF_ROLE: "ACCOUNTADMIN"
         SF_WAREHOUSE: "COMPUTE_WH"
         SF_DATABASE: "SNOWFLAKE_LEARNING_DB"
         SNOWFLAKE_PASSWORD: "MistyStriver@17"
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange
          
          echo "Step 2: Running schemachange"
          schemachange -f $GITHUB_WORKSPACE/snowflake -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
